"""Pinned tree-sitter query patterns per language.

GENERATED by `python3 -m pyedit.patterns --write` from
tests/test_query.py; do not edit. Language to [(test, pattern)].
"""

PATTERNS = {
    "nix": [
        (
            "test_nix_value_hits_feed_splice",
            "(binding (attrpath) @a (integer_expression) @v)",
        ),
        ("test_predicate_filters_hits", '(binding (attrpath) @a (#eq? @a "alpha"))'),
        ("test_hits_arrive_ordered_by_position", "(binding) @b"),
    ],
    "python": [
        ("test_python_function_names", "(function_definition name: (identifier) @n)"),
    ],
    "javascript": [
        (
            "test_javascript_function_names_feed_splice",
            "(function_declaration name: (identifier) @n)",
        ),
    ],
    "typescript": [
        (
            "test_typescript_method_names",
            "(method_definition name: (property_identifier) @n)",
        ),
    ],
    "go": [
        (
            "test_go_function_and_method_names",
            "(function_declaration name: (identifier) @n)",
        ),
        (
            "test_go_function_and_method_names",
            "(method_declaration name: (field_identifier) @n)",
        ),
    ],
    "rust": [
        (
            "test_rust_function_and_struct_names",
            "(function_item name: (identifier) @n)",
        ),
        (
            "test_rust_function_and_struct_names",
            "(struct_item name: (type_identifier) @n)",
        ),
    ],
    "c": [
        (
            "test_c_function_name_feeds_splice",
            "(function_definition declarator: (function_declarator declarator: (identifier) @n))",
        ),
    ],
    "cpp": [
        (
            "test_cpp_function_and_class_names",
            "(function_definition declarator: (function_declarator declarator: (identifier) @n))",
        ),
        (
            "test_cpp_function_and_class_names",
            "(class_specifier name: (type_identifier) @n)",
        ),
    ],
    "java": [
        (
            "test_java_method_and_class_names",
            "(method_declaration name: (identifier) @n)",
        ),
        (
            "test_java_method_and_class_names",
            "(class_declaration name: (identifier) @n)",
        ),
    ],
    "ruby": [
        ("test_ruby_method_and_class_names", "(method name: (identifier) @n)"),
        ("test_ruby_method_and_class_names", "(class name: (constant) @n)"),
    ],
    "lua": [
        ("test_lua_function_name", "(function_declaration name: (identifier) @n)"),
    ],
    "json": [
        ("test_json_pair_keys", "(pair key: (string) @k)"),
    ],
    "yaml": [
        ("test_yaml_mapping_keys", "(block_mapping_pair key: (flow_node) @k)"),
    ],
    "toml": [
        ("test_toml_key_feeds_splice", "(pair (bare_key) @k)"),
    ],
    "bash": [
        ("test_bash_function_name", "(function_definition name: (word) @n)"),
    ],
    "tsx": [
        (
            "test_tsx_function_and_method_names",
            "(function_declaration name: (identifier) @n)",
        ),
        (
            "test_tsx_function_and_method_names",
            "(method_definition name: (property_identifier) @n)",
        ),
    ],
    "zig": [
        ("test_zig_function_name", "(function_declaration name: (identifier) @n)"),
    ],
    "css": [
        (
            "test_css_selector_names_feed_splice",
            "(rule_set (selectors (class_selector) @s))",
        ),
        (
            "test_css_selector_names_feed_splice",
            "(rule_set (selectors (id_selector) @s))",
        ),
    ],
    "fish": [
        ("test_fish_function_name", "(function_definition name: (word) @n)"),
    ],
    "zsh": [
        ("test_zsh_function_name", "(function_definition name: (word) @n)"),
    ],
    "markdown": [
        ("test_markdown_headings_and_fence_language", "(atx_heading) @h"),
        (
            "test_markdown_headings_and_fence_language",
            "(fenced_code_block (info_string (language) @l))",
        ),
    ],
    "svelte": [
        ("test_svelte_tag_names_feed_splice", '((tag_name) @t (#eq? @t "h1"))'),
    ],
}
