"""Pinned tree-sitter query patterns, extracted from the test suite.

tests/test_query.py pins one spelling per shipped language. This
module reads those pins with ast (string literals only, so an
implicit concatenation folds the way the test sees it) and renders
the generated `_patterns.py` that `pyedit patterns` prints. Tests
whose name contains "raises" are negative examples and skipped;
tests without a sample_text() language are usage examples, not
pins, and skipped too.

The golden test fails when the pins and `_patterns.py` disagree;
regenerate with `python3 -m pyedit.patterns --write`.
"""

from __future__ import annotations

import argparse
import ast
import difflib
import sys
from pathlib import Path

GENERATED_HEADER = '''"""Pinned tree-sitter query patterns per language.

GENERATED by `python3 -m pyedit.patterns --write` from
tests/test_query.py; do not edit. Language to [(test, pattern)].
"""
'''


def test_file() -> Path:
    candidate = (
        Path(__file__).resolve().parent.parent.parent / "tests" / "test_query.py"
    )
    if not candidate.is_file():
        raise FileNotFoundError(f"test pins not found at {candidate}")
    return candidate


def generated_path() -> Path:
    return Path(__file__).resolve().parent / "_patterns.py"


def _str_arg(call: ast.Call, index: int) -> str | None:
    if len(call.args) > index and isinstance(call.args[index], ast.Constant):
        value = call.args[index].value
        if isinstance(value, str):
            return value
    return None


def extract(path: Path) -> dict[str, list[tuple[str, str]]]:
    """Map each pinned language to its [(test, pattern)] in file order."""
    tree = ast.parse(path.read_text())
    pins: dict[str, list[tuple[str, str]]] = {}
    for node in tree.body:
        if not isinstance(node, ast.FunctionDef) or "raises" in node.name:
            continue
        language: str | None = None
        found: list[str] = []
        for child in ast.walk(node):
            if not isinstance(child, ast.Call) or not isinstance(child.func, ast.Name):
                continue
            if child.func.id == "sample_text":
                language = _str_arg(child, 0)
            elif child.func.id == "query":
                pattern = _str_arg(child, 2)
                if pattern is not None:
                    found.append(pattern)
        if language is not None and found:
            pins.setdefault(language, []).extend((node.name, p) for p in found)
    return pins


def _quoted(value: str) -> str:
    """Double quotes, unless the value holds some (none holds both kinds)."""
    if '"' in value:
        return repr(value)
    return f'"{value}"'


def render(pins: dict[str, list[tuple[str, str]]]) -> str:
    """The full text `_patterns.py` should have for these pins.

    Ruff-canonical by construction (double quotes, tuples split past
    88 columns), so no format pass ever rewrites the generated file
    and breaks the golden test.
    """
    lines = [GENERATED_HEADER.rstrip("\n"), "", "PATTERNS = {"]
    for language, entries in pins.items():
        lines.append(f"    {_quoted(language)}: [")
        for test, pattern in entries:
            one = f"({_quoted(test)}, {_quoted(pattern)}),"
            if len(one) + 8 <= 88:
                lines.append(f"        {one}")
            else:
                lines.append("        (")
                lines.append(f"            {_quoted(test)},")
                lines.append(f"            {_quoted(pattern)},")
                lines.append("        ),")
        lines.append("    ],")
    lines.append("}")
    return "\n".join(lines) + "\n"


def check(path: Path) -> str:
    """A unified diff when `_patterns.py` drifts, else an empty string."""
    want = render(extract(path))
    have = generated_path().read_text()
    if want == have:
        return ""
    return "".join(
        difflib.unified_diff(
            have.splitlines(keepends=True),
            want.splitlines(keepends=True),
            fromfile="have",
            tofile="want",
        )
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="pyedit.patterns",
        description="Regenerate _patterns.py from the test pins.",
    )
    parser.add_argument(
        "--write",
        action="store_true",
        help="write _patterns.py (default: report drift)",
    )
    args = parser.parse_args(argv)
    if args.write:
        path = generated_path()
        path.write_text(render(extract(test_file())))
        return 0
    drift = check(test_file())
    if drift:
        sys.stdout.write(drift)
        return 1
    sys.stdout.write("patterns are current\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
